# 项目相关配置
df:
  # 名称
  name: DingFlow
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: true
  # 获取ip地址开关
  addressEnabled: true
   # 缓存懒加载
  cacheLazy: false


captcha:
  #验证码开关
  enabled: false
  # 验证码类型 math 数组计算 char 字符验证
  type: MATH
  # line 线段干扰 circle 圆圈干扰 shear 扭曲干扰
  category: CIRCLE
  # 数字验证码位数
  numberLength: 1
  # 字符验证码长度
  charLength: 4

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8

# Spring配置
spring:
  jackson:
    time-zone: GMT+8

  profiles:
    active: dev

  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  main:
    allow-circular-references: true

mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.agee.**.domain
  typeHandlersPackage: com.agee.system.handler
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #全局配置
  global-config:
    db-config:
      #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql