# 项目相关配置
df:
  # 名称
  name: DingFlow
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: true
  # 获取ip地址开关
  addressEnabled: true

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
 
# 日志配置
logging:
  level:
    com.agee: debug
    org.springframework: warn

# Spring配置
spring:
  jackson:
    time-zone: GMT+8

  profiles: 
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  #邮件配置
  mail:
    #mail主机
    host: smtp.126.com
    #用户名
    username: qimingjin@126.com
    #开启POP3之后设置的客户端授权码
    password: JSHBRRRDBNHPXPFB
    default-encoding: UTF-8



mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.agee.**.domain
  typeHandlersPackage: com.agee.system.handler
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:META-INF/modeler-mybatis-mappings/*.xml,classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
  #全局配置
  global-config:
    db-config:
      #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0


